apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service
  namespace: invoice-saas
  labels:
    app: invoice-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
    spec:
      containers:
      - name: invoice-service
        image: invoice-saas-invoice-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: PORT
          value: "3001"
        - name: NODE_ENV
          value: "production"
        - name: SERVICE_NAME
          value: "invoice-service"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: url
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: port
        - name: REDIS_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: auth_token
        - name: AWS_REGION
          value: "us-east-1"
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: s3-bucket-name
        - name: SQS_INVOICE_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: sqs-invoice-queue-url
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-service
  namespace: invoice-saas
  labels:
    app: invoice-service
spec:
  type: ClusterIP
  selector:
    app: invoice-service
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: invoice-service-hpa
  namespace: invoice-saas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: invoice-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
